Repository kjoonas1/Vaalikartta, pull requests merged in 2019-12, with the labels that each got.

#107 Ohje frontendiin
  vaalikartta-frontend/src/App.jsx
  vaalikartta-frontend/src/components/AlertOhje.jsx
  vaalikartta-frontend/src/components/Etusivu.jsx
  vaalikartta-frontend/src/components/Navigation/Navigation.jsx
  vaalikartta-frontend/src/contexts/Contexts.jsx
  vaalikartta-frontend/src/contexts/OhjeContextProvider.jsx
  vaalikartta-frontend/src/dataset/timelineData.js
  vaalikartta-frontend/src/styles/App.scss
Labels: enhancement

#108 Hallituskaudet ministerit v2
  backend/src/routes/routes.js
  vaalikartta-frontend/public/aho.jpg
  vaalikartta-frontend/public/holkeri.jpg
  vaalikartta-frontend/public/jaatteenmaki.jpg
  vaalikartta-frontend/public/katainen.jpg
  vaalikartta-frontend/public/kiviniemi.jpg
  vaalikartta-frontend/public/lipponen.jpg
  vaalikartta-frontend/public/marin.jpg
  vaalikartta-frontend/public/rinne.jpg
  vaalikartta-frontend/public/sipila.jpg
  vaalikartta-frontend/public/sorsa.jpg
  vaalikartta-frontend/public/stubb.jpg
  vaalikartta-frontend/public/vanhanen.jpg
  vaalikartta-frontend/src/components/Charts.jsx
  vaalikartta-frontend/src/components/Hallituskaudet.jsx
  vaalikartta-frontend/src/components/Maps/CountryMap.jsx
  vaalikartta-frontend/src/components/StatisticsTable.jsx
  vaalikartta-frontend/src/dataset/SVGMapParts.jsx
  vaalikartta-frontend/src/styles/App.scss
  vaalikartta-frontend/src/styles/Hallitustiedot.scss
  vaalikartta-frontend/src/styles/Timeline.scss
Labels: enhancement

#111 Korjattu statisticstablen hajoaminen
  backend/src/routes/routes.js
  vaalikartta-frontend/src/components/StatisticsTable.jsx
Labels: bugfix

#110 Readme
  README.md
  backend/package-lock.json
  backend/package.json
  vaalikartta-frontend/package-lock.json
  vaalikartta-frontend/package.json
Labels: documentation

#112 Tietoa sivu
  vaalikartta-frontend/src/components/Tietoa.jsx
Labels: enhancement
